version: 2.1

jobs:
  build:
    environment:
      TAG: "1.2"
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build image
          command: |
            make build
            docker tag wastrachan/arin-waitlist:latest wastrachan/arin-waitlist:$TAG
            docker tag wastrachan/arin-waitlist:latest ghcr.io/wastrachan/arin-waitlist:latest
            docker tag wastrachan/arin-waitlist:latest ghcr.io/wastrachan/arin-waitlist:$TAG

      - run:
          name: Publish image
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
            echo "$GITHUB_PAT" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
            docker push wastrachan/arin-waitlist:latest
            docker push wastrachan/arin-waitlist:$TAG
            docker push ghcr.io/wastrachan/arin-waitlist:latest
            docker push ghcr.io/wastrachan/arin-waitlist:$TAG

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: Docker
          filters:
            branches:
              only: master
